#pragma once

#include "note.h"




namespace instruments {
    enum name {
        acoustic_piano = 0,
        bright_acoustic_piano,
        electric_grand_piano,
        honky_tonk_piano,
        electric_piano_1,
        electric_piano_2,
        harpsichord,
        clavi,
        celesta,
        clockenspiel,
        music_box,
        vibraphone,
        marimba,
        xylophone,
        tubular_bells,
        dulcimer,
        drawbar_organ,
        percussive_organ,
        rock_organ,
        church_organ,
        reed_organ,
        accordion,
        harmonia,
        tango_accordion,
        acoustic_guitar_nylon,
        acoustic_guitar_steel,
        electric_guitar_jazz,
        electric_guitar_clean,
        electric_guitar_muted,
        overdriven_guitar,
        distortion_guitar,
        guitar_harmonics,
        acoustic_bass,
        electric_bass_finger,
        electric_bass_pick,
        fretless_bass,
        slap_bass_1,
        slap_bass_2,
        synth_bass_1,
        synth_bass_2,
        violin,
        viola,
        cello,
        contrabass,
        tremolo_strings,
        pizzicato_strings,
        orchestral_harp,
        timpani,
        string_ensemble_1,
        string_ensemble_2,
        synth_strings_1,
        synth_strings_2,
        choir_aahs,
        voice_oohs,
        synth_voice,
        orchestra_hit,
        trumpet,
        trombone,
        tuba,
        muted_trumpet,
        french_horn,
        brass_section,
        synth_brass_1,
        synth_brass_2,
        soprano_sax,
        alto_sax,
        tenor_sax,
        baritone_sax,
        oboe,
        english_horn,
        bassoon,
        clarinet,
        piccolo,
        flute,
        recorder,
        pan_flute,
        blown_bottle,
        shakuhachi,
        whistle,
        ocarina,
        lead_square,
        lead_sawtooth,
        lead_calliope,
        lead_chiff,
        lead_charang,
        lead_voice,
        lead_fifths,
        lead_bass,
        pad_new_age,
        pad_warm,
        pad_polysynth,
        pad_choir,
        pad_bowed,
        pad_metallic,
        pad_halo,
        pad_sweep,
        fx_rain,
        fx_soundtrack,
        fx_crystal,
        fx_atmosphere,
        fx_brightness,
        fx_goblins,
        fx_echoes,
        fx_sci_fi,
        sitar,
        banjo,
        shamisen,
        koto,
        kalimba,
        bag_pipe,
        fiddle,
        shanai,
        tinkle_bell,
        agogo,
        steel_drums,
        woodblock,
        taiko_drum,
        melodic_tom,
        synth_drum,
        reverse_cymbal,
        guitar_fret_noise,
        breath_noise,
        seashore,
        bird_tweet,
        telephone_ring,
        helicopter,
        applause,
        gunshot,
        SIZE
    };
    enum drums {
        acoustic_bass_drum = 35,
        bass_drum_1,
        side_stick,
        acoustic_snare,
        hand_clap,
        electric_snare,
        low_floor_tom,
        closed_hi_hat,
        high_floor_tom,
        pedal_hi_hat,
        low_tom,
        open_hi_hat,
        low_mid_tom,
        hi_mid_tom,
        crash_cymbal_1,
        high_tom,
        ride_cymbal_1,
        chinese_cymbal,
        ride_bell,
        tambourine,
        splash_cymbal,
        cowbell,
        crash_cymbal_2,
        vibraslap,
        ride_cymbal_2,
        hi_bongo,
        low_bongo,
        mute_hi_conga,
        open_hi_conga,
        low_conga,
        high_timbale,
        low_timbale,
        high_agogo,
        low_agogo,
        cabasa,
        maracas,
        short_whistle,
        long_whistle,
        short_guiro,
        long_guiro,
        claves,
        hi_wood_block,
        low_wood_block,
        mute_cuica,
        open_cuica,
        mute_triangle,
        open_triangle
    };

    static const int bass_regular[] { 32, 33, 34, 35, 36, 37, 38, 39, 43 };
    static const int bass_irregular[] { 0, 4, 7, 18, 24, 58, 87 };
    static const int chord[] { 0, 1, 2, 4, 5, 7, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 40, 41, 44, 45, 48, 49, 50, 51, 52, 53, 54, 56, 61, 73, 75, 88, 89, 90, 91, 92, 93, 94, 95 };

    inline name random_bass() {
        if (chance(95))
            return static_cast<name>(bass_regular[random(0, 8)]);
        return static_cast<name>(bass_irregular[random(0, 6)]);
    }
    inline name random_chord() {
        return static_cast<name>(chord[random(0, 42)]);
    }
    inline name random_melody() {
        return static_cast<name>(random(0, 114));
    }
    inline name random_pad() {
        return static_cast<name>(random(80, 103));
    }
}